# Generated by Django 3.1.2 on 2021-09-23 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_auto_20210918_1525'),
        ('orders', '0004_auto_20210919_0039'),
        ('sample', '0007_auto_20210923_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('order_delivered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField()),
                ('accepted', models.BooleanField(default=False)),
                ('received_date', models.DateField()),
                ('damaged', models.BooleanField(default=False)),
                ('remarks', models.CharField(max_length=1000)),
                ('balance_quantity', models.IntegerField()),
                ('completed_date', models.DateField()),
                ('delivered_by', models.CharField(max_length=1000)),
                ('release_date', models.DateField()),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.orderreceiving')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sample.ladiesfrock')),
            ],
        ),
    ]
