# Generated by Django 3.1.2 on 2021-10-04 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0004_auto_20211003_0028'),
        ('orders', '0004_auto_20210919_0039'),
        ('sample', '0011_auto_20211001_2222'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LadiesStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('order_received', models.DateField()),
                ('remarks', models.CharField(max_length=20000)),
                ('damage', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=True)),
                ('quantity', models.IntegerField(max_length=999999)),
                ('balance_quantity', models.IntegerField(max_length=999999)),
                ('delivery_date', models.DateField()),
                ('order_delivered', models.BooleanField(default=True)),
                ('release_date', models.DateField()),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.orderreceiving')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sample.ladiesfrock')),
            ],
        ),
    ]
