# Generated by Django 3.1.2 on 2021-10-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20211004_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ladiesstock',
            name='balance_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ladiesstock',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
