# Generated by Django 3.1.2 on 2021-10-04 17:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210919_0039'),
        ('sample', '0012_auto_20211004_1846'),
        ('customers', '0004_auto_20211003_0028'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0003_auto_20211004_1526'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LadiesStock',
            new_name='LadiesFrockStock',
        ),
    ]
