# Generated by Django 3.1.2 on 2021-09-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LadiesFrock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='products/ladies-frock/img/')),
                ('sample_manufactured_date', models.DateField()),
                ('style_no', models.CharField(max_length=1000)),
                ('fabric_id', models.CharField(max_length=1000)),
                ('fabric_price', models.DecimalField(decimal_places=2, max_digits=100000)),
                ('consumption', models.CharField(max_length=1000)),
                ('acc_name', models.CharField(max_length=1000)),
                ('acc_id', models.CharField(max_length=1000)),
                ('acc_cost', models.DecimalField(decimal_places=2, max_digits=100000)),
                ('sewing_cost', models.DecimalField(decimal_places=2, max_digits=100000)),
                ('embroidery_cost', models.DecimalField(decimal_places=2, max_digits=100000)),
                ('washed_cost', models.DecimalField(decimal_places=2, max_digits=100000)),
                ('pain_cost', models.DecimalField(decimal_places=2, max_digits=100000)),
                ('factory_profit', models.DecimalField(decimal_places=2, max_digits=100000)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=100000)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
