# Generated by Django 3.1.2 on 2021-09-21 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_boyspant_boysshirt_boysshort_boystshirt_childrensfrock_childrenspant_girlsfrock_girlspant_girlsshort'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ladiesfrock',
            old_name='pain_cost',
            new_name='paint_cost',
        ),
    ]
