# Generated by Django 3.1.2 on 2021-09-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0004_auto_20210922_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='boyspant',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='boysshirt',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='boysshort',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='boystshirt',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='childrensfrock',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='childrenspant',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='girlsfrock',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='girlspant',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='girlsshort',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='girlstshirt',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='infantsfrock',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='infantspant',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kaftan',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ladiesblouse',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ladiesfrock',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ladiespant',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ladiesskirt',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ladiestshirt',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='maternityfrock',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nightwear',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teenfrock',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
    ]
