# Generated by Django 3.1.2 on 2021-09-23 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0004_auto_20210923_1442'),
        ('sample', '0005_auto_20210923_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ladiesfrock',
            name='acc_id',
        ),
        migrations.AddField(
            model_name='ladiesfrock',
            name='accessories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accessories.accsentout'),
        ),
    ]
