# Generated by Django 3.1.2 on 2021-09-23 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabric', '0003_orderout_fabric_id'),
        ('sample', '0006_auto_20210923_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ladiesfrock',
            name='fabric_id',
        ),
        migrations.AddField(
            model_name='ladiesfrock',
            name='fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fabric.orderout'),
        ),
    ]
