# Generated by Django 3.1.2 on 2021-09-29 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0007_auto_20210923_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ladiesblouse',
            old_name='pain_cost',
            new_name='paint_cost',
        ),
    ]
