# Generated by Django 3.1.2 on 2021-09-29 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0008_auto_20210929_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ladiespant',
            old_name='pain_cost',
            new_name='paint_cost',
        ),
    ]
