# Generated by Django 3.1.2 on 2021-09-29 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0009_auto_20210929_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boyspant',
            old_name='pain_cost',
            new_name='paint_cost',
        ),
        migrations.RenameField(
            model_name='boysshirt',
            old_name='pain_cost',
            new_name='paint_cost',
        ),
        migrations.RenameField(
            model_name='boysshort',
            old_name='pain_cost',
            new_name='paint_cost',
        ),
        migrations.RenameField(
            model_name='boystshirt',
            old_name='pain_cost',
            new_name='paint_cost',
        ),
        migrations.RenameField(
            model_name='childrensfrock',
            old_name='pain_cost',
            new_name='paint_cost',
        ),
        migrations.RenameField(
            model_name='childrenspant',
            old_name='pain_cost',
            new_name='paint_cost',
        ),
        migrations.RenameField(
            model_name='girlsfrock',
            old_name='pain_cost',
            new_name='paint_cost',
        ),
        migrations.RenameField(
            model_name='girlspant',
            old_name='pain_cost',
            new_name='paint_cost',
        ),
        migrations.RenameField(
            model_name='girlsshort',
            old_name='pain_cost',
            new_name='paint_cost',
        ),
        migrations.RenameField(
            model_name='girlstshirt',
            old_name='pain_cost',
            new_name='paint_cost',
        ),
        migrations.RenameField(
            model_name='infantsfrock',
            old_name='pain_cost',
            new_name='paint_cost',
        ),
        migrations.RenameField(
            model_name='infantspant',
            old_name='pain_cost',
            new_name='paint_cost',
        ),
        migrations.RenameField(
            model_name='kaftan',
            old_name='pain_cost',
            new_name='paint_cost',
        ),
        migrations.RenameField(
            model_name='ladiesskirt',
            old_name='pain_cost',
            new_name='paint_cost',
        ),
        migrations.RenameField(
            model_name='ladiestshirt',
            old_name='pain_cost',
            new_name='paint_cost',
        ),
        migrations.RenameField(
            model_name='maternityfrock',
            old_name='pain_cost',
            new_name='paint_cost',
        ),
        migrations.RenameField(
            model_name='nightwear',
            old_name='pain_cost',
            new_name='paint_cost',
        ),
        migrations.RenameField(
            model_name='teenfrock',
            old_name='pain_cost',
            new_name='paint_cost',
        ),
    ]
