# Generated by Django 3.1.2 on 2021-10-01 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabric', '0003_orderout_fabric_id'),
        ('sample', '0010_auto_20210929_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boyspant',
            name='fabric_id',
        ),
        migrations.RemoveField(
            model_name='boysshirt',
            name='fabric_id',
        ),
        migrations.RemoveField(
            model_name='boysshort',
            name='fabric_id',
        ),
        migrations.RemoveField(
            model_name='boystshirt',
            name='fabric_id',
        ),
        migrations.RemoveField(
            model_name='childrensfrock',
            name='fabric_id',
        ),
        migrations.RemoveField(
            model_name='childrenspant',
            name='fabric_id',
        ),
        migrations.RemoveField(
            model_name='girlsfrock',
            name='fabric_id',
        ),
        migrations.RemoveField(
            model_name='girlspant',
            name='fabric_id',
        ),
        migrations.RemoveField(
            model_name='girlsshort',
            name='fabric_id',
        ),
        migrations.RemoveField(
            model_name='girlstshirt',
            name='fabric_id',
        ),
        migrations.RemoveField(
            model_name='infantsfrock',
            name='fabric_id',
        ),
        migrations.RemoveField(
            model_name='infantspant',
            name='fabric_id',
        ),
        migrations.RemoveField(
            model_name='kaftan',
            name='fabric_id',
        ),
        migrations.RemoveField(
            model_name='ladiesblouse',
            name='fabric_id',
        ),
        migrations.RemoveField(
            model_name='ladiespant',
            name='fabric_id',
        ),
        migrations.RemoveField(
            model_name='ladiesskirt',
            name='fabric_id',
        ),
        migrations.RemoveField(
            model_name='ladiestshirt',
            name='fabric_id',
        ),
        migrations.RemoveField(
            model_name='maternityfrock',
            name='fabric_id',
        ),
        migrations.RemoveField(
            model_name='nightwear',
            name='fabric_id',
        ),
        migrations.RemoveField(
            model_name='teenfrock',
            name='fabric_id',
        ),
        migrations.AddField(
            model_name='boyspant',
            name='fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fabric.orderout'),
        ),
        migrations.AddField(
            model_name='boysshirt',
            name='fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fabric.orderout'),
        ),
        migrations.AddField(
            model_name='boysshort',
            name='fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fabric.orderout'),
        ),
        migrations.AddField(
            model_name='boystshirt',
            name='fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fabric.orderout'),
        ),
        migrations.AddField(
            model_name='childrensfrock',
            name='fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fabric.orderout'),
        ),
        migrations.AddField(
            model_name='childrenspant',
            name='fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fabric.orderout'),
        ),
        migrations.AddField(
            model_name='girlsfrock',
            name='fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fabric.orderout'),
        ),
        migrations.AddField(
            model_name='girlspant',
            name='fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fabric.orderout'),
        ),
        migrations.AddField(
            model_name='girlsshort',
            name='fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fabric.orderout'),
        ),
        migrations.AddField(
            model_name='girlstshirt',
            name='fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fabric.orderout'),
        ),
        migrations.AddField(
            model_name='infantsfrock',
            name='fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fabric.orderout'),
        ),
        migrations.AddField(
            model_name='infantspant',
            name='fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fabric.orderout'),
        ),
        migrations.AddField(
            model_name='kaftan',
            name='fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fabric.orderout'),
        ),
        migrations.AddField(
            model_name='ladiesblouse',
            name='fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fabric.orderout'),
        ),
        migrations.AddField(
            model_name='ladiespant',
            name='fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fabric.orderout'),
        ),
        migrations.AddField(
            model_name='ladiesskirt',
            name='fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fabric.orderout'),
        ),
        migrations.AddField(
            model_name='ladiestshirt',
            name='fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fabric.orderout'),
        ),
        migrations.AddField(
            model_name='maternityfrock',
            name='fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fabric.orderout'),
        ),
        migrations.AddField(
            model_name='nightwear',
            name='fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fabric.orderout'),
        ),
        migrations.AddField(
            model_name='teenfrock',
            name='fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fabric.orderout'),
        ),
    ]
