# Generated by Django 3.1.2 on 2021-09-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecievedIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_received', models.DateField()),
                ('date_order_delivered', models.DateField()),
                ('style_no', models.CharField(max_length=1000)),
                ('order_no', models.CharField(max_length=1000)),
                ('remarks', models.CharField(max_length=9000)),
                ('required_date', models.DateField()),
                ('fabric_type', models.CharField(max_length=1000)),
                ('customer_name', models.CharField(max_length=1000)),
                ('consumption', models.CharField(max_length=1000)),
                ('total_consumption', models.CharField(max_length=1000)),
                ('delivery_date', models.DateField()),
                ('time', models.BooleanField()),
                ('user_notes', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='SentOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_received', models.DateField()),
                ('date_order_delivered', models.DateField()),
                ('style_no', models.CharField(max_length=1000)),
                ('order_no', models.CharField(max_length=1000)),
                ('remarks', models.CharField(max_length=9000)),
                ('required_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('fabric_type', models.CharField(max_length=1000)),
                ('customer_name', models.CharField(max_length=1000)),
                ('consumption', models.CharField(max_length=1000)),
                ('total_consumption', models.CharField(max_length=1000)),
                ('delivery_date', models.DateField()),
                ('time', models.BooleanField()),
                ('user_notes', models.CharField(max_length=10000)),
            ],
        ),
    ]
