# Generated by Django 3.1.2 on 2021-09-16 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cutting', '0002_auto_20210916_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentout',
            old_name='order_received',
            new_name='order_recieved',
        ),
    ]
