# Generated by Django 3.1.2 on 2021-09-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric', '0002_auto_20210919_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderout',
            name='fabric_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
