# Generated by Django 3.1.2 on 2021-09-18 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210919_0039'),
        ('sewing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sewing',
            name='order_no',
        ),
        migrations.AddField(
            model_name='sewing',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.orderreceiving'),
        ),
    ]
