# Generated by Django 3.1.2 on 2021-09-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210918_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email_type',
            field=models.CharField(choices=[('work', 'Work'), ('personal', 'Personal')], default='Work', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile_no_type',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('home', 'Home'), ('work', 'Work')], default='Mobile', max_length=10),
        ),
    ]
