# Generated by Django 3.1.2 on 2021-09-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccRecievedIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('invoice_no', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100000)),
                ('quantity', models.IntegerField()),
                ('vale', models.IntegerField()),
                ('customer_name', models.CharField(max_length=1000)),
                ('customer_id', models.CharField(max_length=1000)),
                ('delivery_date', models.DateField()),
                ('time', models.CharField(max_length=1000)),
                ('user_notes', models.CharField(max_length=9000)),
            ],
        ),
        migrations.CreateModel(
            name='AccSentOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('invoice_no', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100000)),
                ('quantity', models.IntegerField()),
                ('vale', models.IntegerField()),
                ('customer_name', models.CharField(max_length=1000)),
                ('customer_id', models.CharField(max_length=1000)),
                ('delivery_date', models.DateField()),
                ('time', models.CharField(max_length=1000)),
                ('user_notes', models.CharField(max_length=9000)),
            ],
        ),
    ]
