# Generated by Django 3.1.2 on 2021-09-15 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accrecievedin',
            old_name='vale',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='accsentout',
            old_name='vale',
            new_name='value',
        ),
    ]
