# Generated by Django 3.1.2 on 2021-09-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReceiving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_received', models.DateTimeField()),
                ('date_order_delivered', models.DateTimeField()),
                ('style_no', models.CharField(max_length=1000)),
                ('order_no', models.CharField(max_length=1000)),
                ('remarks', models.CharField(max_length=9000)),
                ('required_date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('customer_name', models.CharField(max_length=1000)),
                ('customer_id', models.CharField(max_length=1000)),
                ('consumption', models.CharField(max_length=1000)),
                ('total_consumption', models.CharField(max_length=1000)),
                ('delivery_date', models.DateTimeField()),
                ('order_status', models.BooleanField(default=False)),
                ('order_progress', models.CharField(max_length=1000)),
                ('reason', models.CharField(max_length=1000)),
            ],
        ),
    ]
