# Generated by Django 3.1.2 on 2021-09-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreceiving',
            name='date_order_delivered',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='orderreceiving',
            name='delivery_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='orderreceiving',
            name='order_received',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='orderreceiving',
            name='required_date',
            field=models.DateField(),
        ),
    ]
