# Generated by Django 3.1.2 on 2021-09-18 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20210918_1525'),
        ('orders', '0002_auto_20210914_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderreceiving',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='orderreceiving',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='orderreceiving',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
            preserve_default=False,
        ),
    ]
