# Generated by Django 3.1.2 on 2021-09-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('invoice_no', models.CharField(max_length=1000)),
                ('customer_name', models.CharField(max_length=1000)),
                ('customer_id', models.CharField(max_length=1000)),
                ('style_no', models.CharField(max_length=1000)),
                ('order_no', models.CharField(max_length=1000)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('value', models.IntegerField()),
                ('method_of_payment', models.CharField(choices=[('cash', 'CASH'), ('check', 'CHECK')], default='Cash', max_length=100)),
            ],
        ),
    ]
