# Generated by Django 3.1.2 on 2021-09-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='method_of_payment',
            field=models.CharField(choices=[('cash', 'Cash'), ('check', 'Check')], default='Cash', max_length=100),
        ),
    ]
