# Generated by Django 3.1.2 on 2021-09-18 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20210918_1525'),
        ('invoice', '0002_auto_20210915_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_first_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_customer_first_name_set', to='customers.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_last_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
            preserve_default=False,
        ),
    ]
