# Generated by Django 3.1.2 on 2021-09-18 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_auto_20210919_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='customer_last_name',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='customer_first_name',
        ),
    ]
