# Generated by Django 3.1.2 on 2021-09-18 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210919_0022'),
        ('invoice', '0004_auto_20210919_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='order_no',
        ),
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.orderreceiving'),
        ),
    ]
